apiVersion: autoscaling.x-k8s.io/v1alpha1
kind: StartupCPUBoost
metadata:
  name: boost-001
  namespace: serverless
selector:
  matchExpressions:
  - key: serving.knative.dev/service
    operator: In
    values: ["measure-yolo"]
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: user-container
      fixedResources:
        - node: node1
          requests: "200m"
          limits: "500m"
        - node: node2
          requests: "200m"
          limits: "500m"
  durationPolicy:
    apiCondition:
      url: "http://measure-yolo.serverless.svc.cluster.local/status"
      response: "READY"