apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: measure-yolo-003
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 10s
        autoscaling.knative.dev/min-scale: '0'
        autoscaling.knative.dev/max-scale: '1'
    spec:
      containerConcurrency: 1
      nodeSelector:
        kubernetes.io/hostname: "worker"
      containers:
        - image: docker.io/lazyken/measure-yolo:v1@sha256:b89f025e9b7bd7181ba51cf7d6006f6b550d719b0fea578309cbdbd2b9e9a884
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "100m"
          ports:
            - containerPort: 8080
          env:
            - name: RTMP_STREAM_URL
              value: '192.168.17.129:2000'